#!/bin/bash
#PBS -N add_slope_2
#PBS -l nodes=1:ppn=25
#PBS -j n
#PBS -l walltime=5:00:00
cd $PBS_O_WORKDIR

NP=`cat $PBS_NODEFILE | wc -l`

mpiexec -n $NP -hostfile $PBS_NODEFILE python add_slope_2.py -i /public/home/mfeng/jwang/forest/northeast/tcc/tcc_new -o /public/home/mfeng/jwang/forest/northeast/out/slope/2 -pm /public/home/mfeng/jwang/forest/northeast/out/mean/1 -ps /public/home/mfeng/jwang/forest/northeast/out/slope/1 -n $NP