#!/bin/bash
#PBS -N fykx_clip
#PBS -l nodes=2:ppn=20
#PBS -j n
#PBS -l walltime=5:00:00
cd $PBS_O_WORKDIR

NP=`cat $PBS_NODEFILE | wc -l`

mpiexec -n $NP -hostfile $PBS_NODEFILE python clip.py -i /public/home/mfeng/jwang/forest/northeast/tcc/tcc_new/data -o /public/home/mfeng/jwang/forest/northeast/tcc/tcc_new/clip_data -m /public/home/mfeng/jwang/forest/northeast/tcc/ne_shp/NE_WGS1984.shp -s tcc_new -n $NP
